### ISSUE TITLE
presimulation check failures and Model Input File

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#10]
Hi SEEKR2 team,
For the trypsin-benzamidine tutorial, I reached the stage of creating a "Model Input File" to run the "prepare.py, run.py, converge.py and analyze.py" scripts. 
I've copied the input_tryp_ben_mmvt.xml file from seekr2/seekr2/data/trypsin_benzamidine_files.
Then, I gave the full path for all the anchor pdb files (smd_atXXX.pdb) in this xml file?
Then I reorder the numbers given in anchor-radius to match the smd file names. This did not give any error, thus I'm assuming this is correct, is it? PDB files created during all earlier steps are shown below.

in the input preparation step, I forgot to mention that antechamber failed with benzamidine pdb file and I added the missing polar hydrogen using GaussView5 to make benzamidiine +vely charged after which it ran correctly.  Thus you may want to check the structure available on the tutorial (or pdb website) page and its behavior during parameter generation. 

Please let me know if this step is likely to be the cause of errors in the presimulation checks.
If that is the case, then I will have to restart from the first step of the tutorial, right?
I am unable to attached sample files that I'm using here.
I can send them over the email in case it is required to do some checking at your end.
Please let me know if it is ok to simply use the "-s" flag to skip these check (I think it might not be a good idea).
Looking forward to your valuable suggestions.
Thank you and best regards, Vaibhav

(SEEKR) [exx@c107739 trypsin-benzamidine]$ ls -arlth *.pdb
-rw-rw-r--. 1 exx exx 250K Sep  4 16:07 3ptb_processed.pdb
-rw-rw-r--. 1 exx exx  711 Sep  4 18:00 BEN.pdb
-rw-rw-r--. 1 exx exx 1.9K Sep  4 18:13 BEN-H.pdb
-rw-rw-r--. 1 exx exx 1.9K Sep  4 18:14 BEN-H1.pdb
-rw-rw-r--. 1 exx exx 1.4K Sep  4 18:15 sqm.pdb
-rw-rw-r--. 1 exx exx 1.6K Sep  4 19:43 tryp_ben_ligand_one_resid_nonprot.pdb
-rw-rw-r--. 1 exx exx 243M Sep  5 02:38 equilibration_trajectory.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:12 tryp_ben.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:13 equilibrated.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:45 smd_at0.15.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:08 smd_at0.25.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:26 smd_at0.35.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:53 smd_at0.45.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 14:57 smd_at0.75.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 15:20 smd_at0.85.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 16:28 smd_at1.15.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 16:55 smd_at1.25.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 18:03 smd_at1.55.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 18:21 smd_at1.65.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 19:34 smd_at1.95.pdb
-rw-rw-r--. 1 exx exx 173M Sep  8 19:34 smd_trajectory.pdb

(SEEKR) [exx@c107739 trypsin-benzamidine]$ python3.8 /home/exx/Downloads/seekr2/seekr2/prepare.py input_tryp_ben_mmvt.xml 
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
CHECK FAILURE: BD simulation has significantly different
    ionic strength of 0.120 M*e^2 than MD simulation ionic strength of 
    0.061 M*e^2 for anchor 0. Please check the ion concentrations in the 
    BD simulation settings, and also count the number of ions 
    in the MD simulations. Counterions added to neutralize the protein in an
    MD simulation may also trigger this failure. If that is the case, simply 
    skip this check.
One or more fatal pre-simulation checks failed. It is highly recommended that you address and correct each of these problems. However, you can force SEEKR to skip these checks by using the --skip_checks (-s) argument on prepare.py.
Traceback (most recent call last):
  File "/home/exx/Downloads/seekr2/seekr2/prepare.py", line 86, in <module>
    check.check_pre_simulation_all(model)
  File "/home/exx/anaconda3/envs/SEEKR/lib/python3.8/site-packages/seekr2-0+untagged.144.ge74fc0f-py3.8.egg/seekr2/modules/check.py", line 749, in check_pre_simulation_all
    raise Exception("The SEEKR2 calculation can not proceed due "\
Exception: The SEEKR2 calculation can not proceed due to failed pre-simulation checks.
(SEEKR) [exx@c107739 trypsin-benzamidine]$

**Comment by lvotapka** [comment]
It sounds like you did everything right, and that you can ignore this check failure. The checks are designed to catch common input mistakes and, in this check, catches mismatches between salt concentrations between BD vs MD. However, if this was intentional, and the MD has the number of ions you want, and BD has the defined salt concentrations you want, then you can skip this check with the "-s" argument. (Or just move ahead because a check failure still generates the full model with all its files). If you don't want to ignore this check, you can add salt ions in the LEAP step, or change the ion concentrations in the BD portion of the input file until the two stages match.

As for the Antechamber problem you encountered, would you be able to send us that error output? I tested those tutorials and I didn't run into that particular issue.

**Comment by vaibhavadixit** [comment]
Hi @lvotapka 
The ligand structure available on the tutorial website has 3 Hs on the Ns which makes the molecule neutral.
But in the antechamber command it has -nc 1 flag which expects the molecule to be +vely charged and thus have 4 Hs.
The cif file from the pdb website is for the neutral state i.e. has 3 Hs, thus the antechamber command would fail (due to mismtach between the number of electrons and charge in the ligand) unless you have already added 1 more H.

This is the reason I'm suspecting this to be the source of failure in presimulation check.

I tried with -s option, but it failed again. I will try the next step anyways as you suggested and let you know if it fails.
Please let me know if I misunderstood the antechamber step.
thank you and best regards.
Vaibhav

**Comment by vaibhavadixit** [comment]
Hi,
I tried with the -s option, although did not return any error and only a state.xml file was created.
This isn't the model-input file, right? Since following, attempts are not working.
Please suggest how to proceed further.
thank you and best regards.

(SEEKR) [exx@c107739 trypsin-benzamidine]$ python3.8 /home/exx/Downloads/seekr2/seekr2/prepare.py input_tryp_ben_mmvt.xml -s
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
(SEEKR) [exx@c107739 trypsin-benzamidine]$ ls -arlth
total 458M
-rw-rw-r--. 1 exx exx 250K Sep  4 16:07 3ptb_processed.pdb
drwxrwxr-x. 3 exx exx 4.0K Sep  4 16:08 ..
-rw-rw-r--. 1 exx exx 5.4K Sep  4 17:52 BEN.cif
-rw-rw-r--. 1 exx exx  711 Sep  4 18:00 BEN.pdb
-rw-rw-r--. 1 exx exx 1.9K Sep  4 18:13 BEN-H.pdb
-rw-rw-r--. 1 exx exx 1.9K Sep  4 18:14 BEN-H1.pdb
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_BOND_TYPE.AC0
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_BOND_TYPE.AC
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_AC.AC0
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_AC.AC
-rw-rw-r--. 1 exx exx 1.1K Sep  4 18:15 sqm.in
-rw-rw-r--. 1 exx exx 7.0K Sep  4 18:15 sqm.out
-rw-rw-r--. 1 exx exx 1.4K Sep  4 18:15 sqm.pdb
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_AM1BCC_PRE.AC
-rw-rw-r--. 1 exx exx 4.7K Sep  4 18:15 ATOMTYPE.INF
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 ANTECHAMBER_AM1BCC.AC
-rw-rw-r--. 1 exx exx 2.1K Sep  4 18:15 benz.mol2
-rw-rw-r--. 1 exx exx  792 Sep  4 18:51 benz.frcmod
-rw-rw-r--. 1 exx exx 3.2K Sep  4 18:51 benz.lib
-rw-rw-r--. 1 exx exx  419 Sep  4 18:55 trypsin-benamidine-tleap.txt
-rw-rw-r--. 1 exx exx  29K Sep  4 18:57 leap.log
-rw-rw-r--. 1 exx exx 1.9M Sep  4 19:15 tryp_ben_all.pqr
-rw-rw-r--. 1 exx exx 1.5K Sep  4 19:40 BEN.pqr
-rw-rw-r--. 1 exx exx   23 Sep  4 19:43 tryp_ben_ligand_one_resid_renum.txt
-rw-rw-r--. 1 exx exx    0 Sep  4 19:43 tryp_ben_ligand_one_resid_sslink
-rw-rw-r--. 1 exx exx 1.6K Sep  4 19:43 tryp_ben_ligand_one_resid_nonprot.pdb
-rw-rw-r--. 1 exx exx 1.4K Sep  4 19:43 tryp_ben_ligand_one_resid.pqr
-rw-rw-r--. 1 exx exx 5.7K Sep  4 20:24 tryp_ben_equil.py
-rw-rw-r--. 1 exx exx 5.7M Sep  4 21:24 molecule_TMP.parm7
-rw-rw-r--. 1 exx exx 1.1M Sep  4 21:24 molecule_TMP.rst7
-rw-rw-r--. 1 exx exx 1.1M Sep  5 02:38 equilibrated.rst7
-rw-rw-r--. 1 exx exx 243M Sep  5 02:38 equilibration_trajectory.pdb
-rw-rw-r--. 1 exx exx 6.7K Sep  7 01:11 tryp_ben_smd.py
-rw-rw-r--. 1 exx exx 4.6M Sep  8 12:12 tryp_ben.prmtop
-rw-rw-r--. 1 exx exx 822K Sep  8 12:12 tryp_ben.inpcrd
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:12 tryp_ben.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:13 equilibrated.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 12:45 smd_at0.15.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:08 smd_at0.25.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:26 smd_at0.35.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 13:53 smd_at0.45.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 14:57 smd_at0.75.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 15:20 smd_at0.85.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 16:28 smd_at1.15.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 16:55 smd_at1.25.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 18:03 smd_at1.55.pdb
-rw-rw-r--. 1 exx exx 1.8M Sep  8 18:21 smd_at1.65.pdb
-rw-rw-r--. 1 exx exx 3.7M Sep  8 19:34 state.xml
-rw-rw-r--. 1 exx exx 1.8M Sep  8 19:34 smd_at1.95.pdb
-rw-rw-r--. 1 exx exx 173M Sep  8 19:34 smd_trajectory.pdb
drwxrwxr-x. 2 exx exx 4.0K Sep  9 12:23 images_and_plots
-rw-rw-r--. 1 exx exx  12K Sep  9 13:10 input_tryp_ben_mmvt.xml
-rw-rw-r--. 1 exx exx 1.5K Sep  9 22:36 tryp_ben_ligand.pqr
-rw-rw-r--. 1 exx exx 255K Sep  9 22:39 tryp_ben_receptor.pqr
drwxrwxr-x. 3 exx exx 4.0K Sep  9 22:39 .
(SEEKR) [exx@c107739 trypsin-benzamidine]$ 

(SEEKR) [exx@c107739 trypsin-benzamidine]$ python3.8 /home/exx/Downloads/seekr2/seekr2/run.py state.xml 
usage: run.py [-h] [-c CUDA_DEVICE_INDEX] [-t MIN_TOTAL_SIMULATION_LENGTH] [-T MAX_TOTAL_SIMULATION_LENGTH] [-C CONVERGENCE_CUTOFF]
              [-m MINIMUM_ANCHOR_TRANSITIONS] [-d DIRECTORY] [-f] [-s] [-S] [-n NAMD_COMMAND] [-a NAMD_ARGUMENTS]
              [-b MINIMUM_B_SURFACE_TRAJECTORIES] [-y MIN_B_SURFACE_ENCOUNTERS] [-l NUM_REV_LAUNCHES] [-u]
              INSTRUCTION MODEL_FILE
run.py: error: the following arguments are required: MODEL_FILE
(SEEKR) [exx@c107739 trypsin-benzamidine]$

**Comment by lvotapka** [comment]
Yes, if there are 3 H's on the benzamidine, then it is indeed neutral. However, in the case of this tutorial, I believe that the Antechamber and LEAP commands will automatically add the fourth H to make the benzamidine molecule positively charged. So I don't think you need to add the H manually.

As for the run command you are attempting, you will need to look in the input XML file and find the "root_directory" tag near the top. This directory is where a "model.xml" file will be written. This needs to be the input to all subsequent programs.

The run.py program also needs an "instruction" argument, such as "any", "any_md", "any_bd", etc. to tell it which simulations to run. The instruction argument comes before the model file argument.

So a sample command for you would look like:

```
python3.8 /home/exx/Downloads/seekr2/seekr2/run.py any /path/to/model.xml
```

**Comment by vaibhavadixit** [comment]
Dear Lane,
thanks for clarification on the usage.
With my experience in Amber (which is not that bad), I'm sure antechamber
doesn't add any Hs at all and leap will do only based on the libraries
sourced. Even tleap can't add Hs according to pH.  Amber developers
recommend "reduce" to add standard Hs and use other programs like H++ for
correct protonation states for specific pH.

With correct usage and paths seekr2 looks running ok, but I think it is
better to make sure that either presimulation checks are ok or I understand
exactly what I'm doing.
thanks and best regards.

(SEEKR) ***@***.*** trypsin-benzamidine]$ python3.8
/home/exx/Downloads/seekr2/seekr2/run.py any
~/tryp_ben_mmvt_seekr2_18_atoms/model.xml &
[1] 25042
(SEEKR) ***@***.*** trypsin-benzamidine]$ anchor 0 has not run the minimum
number of steps 0 of 250000000
anchor 1 has not run the minimum number of steps 0 of 250000000
anchor 2 has not run the minimum number of steps 0 of 250000000
anchor 3 has not run the minimum number of steps 0 of 250000000
anchor 4 has not run the minimum number of steps 0 of 250000000
anchor 5 has not run the minimum number of steps 0 of 250000000
anchor 6 has not run the minimum number of steps 0 of 250000000
anchor 7 has not run the minimum number of steps 0 of 250000000
anchor 8 has not run the minimum number of steps 0 of 250000000
anchor 9 has not run the minimum number of steps 0 of 250000000
anchor 10 has not run the minimum number of steps 0 of 250000000
running anchor_index: 0 restart: False total_simulation_length: 250000000
num_transitions: 0

Regards,

Dr. Vaibhav A. Dixit,

Visiting Scientist at the Manchester Institute of Biotechnology (MIB), The
University of Manchester, 131 Princess Street, Manchester M1 7DN, UK.
AND
Assistant Professor,
Department of Pharmacy,
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Birla Institute of Technology and Sciences Pilani (BITS-Pilani),
VidyaVihar Campus, street number 41, Pilani, Rajasthan 333031.
India.
Phone No. +91 1596 255652, Mob. No. +91-7709129400,
Email: ***@***.***, ***@***.***
http://www.bits-pilani.ac.in/pilani/vaibhavdixit/profile
https://www.linkedin.com/in/vaibhav-dixit-b1a07a39/

ORCID ID: https://orcid.org/0000-0003-4015-2941

NCBI bibliography:
https://www.ncbi.nlm.nih.gov/myncbi/1Jgo56b26_AYKd/bibliography/public/

http://scholar.google.co.in/citations?user=X876BKcAAAAJ&hl=en&oi=sra

P Please consider the environment before printing this e-mail

**Comment by lvotapka** [comment]
After looking into the Antechamber issue with missing hydrogens on the benzamidine, I see that you are correct. Thank you for bringing this to my attention. I've fixed the tutorial to use a different input to Antechamber which now has the missing hydrogens.

As a side note, all of our publications used a parametrized benzamidine molecule that contained the correct protonation state, so this problem wouldn't have affected any of our published or submitted data.

**Comment by vaibhavadixit** [comment]
that's great. I'm glad that I'm able to help as I'm learning SEEKR.
Also good to know that this minor issue didn't impact the main results.

Nonetheless, I'm just wondering that such a point might lead to errors in pre-simulation checks if appropriate ions are not introduced while creating parameters with tleap script.
I will let you know if I encounter other errors or have difficulty in understanding how the next steps are supposed to work.
thanks and best regards.

**Comment by vaibhavadixit** [comment]
Hi,
The SEEKR2 tutorial and even the tests (during installation) were for the host-guest system and not for the trypsin-benzamidine system, right?
Thus can you please comment on how long the run.py, converge.py and analyze steps are likely to take for this protein-ligand system?  The run.py step has been running for about 6 hours now and it has print only the following.
thanks and best regards. Vaibhav

anchor 0 has not run the minimum number of steps 2500000 of 250000000
anchor 1 has not run the minimum number of steps 12500000 of 250000000
anchor 2 has not run the minimum number of steps 0 of 250000000
anchor 3 has not run the minimum number of steps 0 of 250000000
anchor 4 has not run the minimum number of steps 0 of 250000000
anchor 5 has not run the minimum number of steps 0 of 250000000
anchor 6 has not run the minimum number of steps 0 of 250000000
anchor 7 has not run the minimum number of steps 0 of 250000000
anchor 8 has not run the minimum number of steps 0 of 250000000
anchor 9 has not run the minimum number of steps 0 of 250000000
anchor 10 has not run the minimum number of steps 0 of 250000000
running anchor_index: 2 restart: False total_simulation_length: 250000000 num_transitions: 0
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)"
2500000,-250394.01307666907,296.4406852444088,177.84127115140652
5000000,-251292.20480102557,295.1846639974495,177.84127115140652
7500000,-251556.9937043588,299.14293145856306,177.84127115140652
10000000,-250940.8949151542,298.35382420322935,177.84127115140652
12500000,-250517.7132275137,299.36148474656926,177.84127115140652
15000000,-251269.89918275317,293.66849431780963,177.84127115140652
17500000,-249927.39225638285,296.9048922212771,177.84127115140652
20000000,-250905.70402291138,298.4634093304751,177.84127115140652
22500000,-250792.07337615825,298.743581765254,177.84127115140652
25000000,-250415.4904485247,296.43577520945206,177.84127115140652
27500000,-250264.490949278,299.79851769772387,177.84127115140652

**Comment by lvotapka** [comment]
It looks like for this system you completed 27,500,000 steps so far, which is 55 ns in 6 hours, so this is approx. 220 ns/day. It looks like this is running 500 ns per anchor, with a total of 10 anchors, so if you keep running it like this, it will take you 23 days. For this reason, if this is just a test, you should probably reduce the number of steps. But if this were an actual production run, you should spread this calculation over multiple GPUs. You can do this by using an integer in the run.py script instead of the "any" instruction and the "-c" argument.

Example (for a node with 4 GPUs):
```
SEEKR_DIR="/path/to/seekr2/seekr2"
PROJECT_ROOT_DIR="/path/to/project/"
python $SEEKR_DIR/run.py 0 $PROJECT_ROOT_DIR/model.xml -c 0 &
python $SEEKR_DIR/run.py 1 $PROJECT_ROOT_DIR/model.xml -c 1 &
python $SEEKR_DIR/run.py 2 $PROJECT_ROOT_DIR/model.xml -c 2 &
python $SEEKR_DIR/run.py 3 $PROJECT_ROOT_DIR/model.xml -c 3 &
wait
```

The first integer specifies the index of the anchor to run. The second integer (after the "-c" argument) indicates which GPU to use for the simulation.

The good news is that SEEKR2 makes constant checkpoints and will automatically pick up where it left off if you kill this job and move it to a GPU cluster or somewhere to restart it with more GPUs.

**Comment by vaibhavadixit** [comment]
Hi,
I just wanted to test the installation and walk through all the steps in
the tutorial. Then probably I would have to read the papers carefully to
understand the underlying theory, then evaluate the feasibility for the
system that I really want to make predictions on.
My hardware resources are not that great, just a couple of GPUs.
Nonetheless I have some funds to pay for GPU time on a cloud service like
Google.
Please let me know your thoughts on the technical feasibility of this Idea
and also on IPR policy of major software dependencies and any other aspects
that I might have missed here. I might be thinking ahead of myself here,
thus I can create a separate issue or discuss this via email if not
relevant on the GitHub forum.
Thanks and best regards.

**Comment by lvotapka** [comment]
Alright, if you're just doing a test, then you can easily adjust the number of steps to run per anchor by using the "-t" argument for run.py.

Example (will run 1 ns per anchor):
```
python /path/to/seekr2/seekr2/run.py any /path/to/model.xml -t 500000
```

As for getting it to run on a cloud service like Google, I think that should work just fine. The tricky thing with SEEKR2 is, always, the installation. Although we should have a docker image available soon if that will make installation easier. As long as the operating system of the server is a recent version of Linux, with Python3.8 or later, and the ability to use CUDA 10.2 or later, SEEKR2 should work.

**Comment by vaibhavadixit** [comment]
OK, this sounds great.
Please do alert me when the docker image is available. 
In the meantime, I will try to learn more about Docker containers and how people use cloud services to run github programs/tools.
Thank and best regards.
