### ISSUE TITLE
attribute error in analyze.py

### ISSUE THREAD

**Issue by bensebaer** [seekrcentral/seekr2#11]
Hi Lane,
I tried to use analyze.py on some seerk2 directories but everytime I observe a weird error:

#Input
python ~/Software/seekr2-conda/seekr2/analyze.py model.xml 

#Output
Traceback (most recent call last):
  File "/home/g035896/Software/seekr2-conda/seekr2/analyze.py", line 801, in <module>
    image_directory = common_analyze.make_image_directory(
AttributeError: module 'seekr2.modules.common_analyze' has no attribute 'make_image_directory'

Before executing analyze.py, I have pulled the latest seekr2-code by 'git pull' and 'python setup.py install'. I also regenerated the model-file by 'prepare.py' but observed no change.

From looking into the code, I assume these two lines are causing the error:

  model = base.load_model(model_file)
  image_directory = common_analyze.make_image_directory(
        model, image_directory)

'image_directory' seems to fail because it is missing the 'model' attribute.

**Comment by lvotapka** [comment]
Yes, I just made this code change, and I ran into this problem myself, but a reinstall fixed it for me. Would you mind doing a "git pull" and then a "python setup.py install" one more time just to be sure that won't fix the problem?

**Comment by lvotapka** [comment]
Hi @bensebaer I just wanted to follow up on this issue, since it's been about a week since you opened it. Were you able to get this issue resolved? If so, was it the suggested procedure that resolved it or another solution?

**Comment by bensebaer** [comment]
Hi Lane, 
sorry for my late reply. The issue was resolved by updating the code. I still don't understand how it didn*t work the first time. 

Thank you for your help!
Jens
