### ISSUE TITLE
query about tutorial simulation time trypsin-benzamidine

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#12]
Dear @lvotapka and SEEKR2 team,
I resubmitted the tutorial calculation with -t 500000 flag so that MD runs for only 1ns (as a test).
Now It seems like SEEKR2 has been running the BD part for ~6 hrs with n_threads=6.
Since I've limited experience in both BD and milestoning, it will be good to know how long one can expect the BD component to run.
What is the default sequence in SEEKR for the BD and MD simulations? If I understood correctly, the MD and BD runs are not explicitly dependent on each other (MD for active site and BD from protein surface to g-surface i.e. infinity).
Thus is it possible to run both simultaneously BD on CPU and MD on GPUs to save time?

For newer protein-ligand systems, in testing mode, will it make sense to reduce the MD convergence criteria and other parameters in addition to the -t flag, in order to first check whether the simulation step is ok or not?

The output of the command is below at the end.
Looking forward to your valuable suggestions and comments.
thank you and best regards, Vaibhav

 
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                 
13163 exx       20   0  477940  41396   2620 S 601.0  0.1   1890:57 nam_simulation receptor_ligand_simulation.xml  

(SEEKR) [exx@c107739 trypsin-benzamidine]$ python3.8 /home/exx/Downloads/seekr2/seekr2/run.py any model.xml -t 500000 > runstep-output.log &
(SEEKR) [exx@c107739 trypsin-benzamidine]$ cat runstep-output.log
command surface_spheres -probe_radius 1.5 < tryp_ben_receptor.xml > receptor_surface.xml
command inside_points -spheres tryp_ben_receptor.xml -surface receptor_surface.xml -egrid receptor1.dx > receptor_inside.xml
command hydro_params < receptor_inside.xml > receptor_hydro_params.xml
command test_charges < tryp_ben_receptor.xml > receptor_charges.xml
command lumped_charges -pts receptor_charges.xml > receptor_cheby.xml
command make_surface_sphere_list -surface receptor_surface.xml -spheres tryp_ben_receptor.xml -rxn rxns.xml -group receptor -core receptor > receptor_surface_atoms.xml
command mpole_grid_fit -dx receptor0.dx -solvdi 78 -debye 8.75563 > receptor_mpole.xml
command born_integral -in receptor_inside.xml -oeps 78 -debye 8.75563 -ieps 4.000000 > receptor_born.dx
command compute_charges_squared < receptor_charges.xml > receptor_charges_squared.xml
command lumped_charges -pts receptor_charges_squared.xml > receptor_squared_cheby.xml
command surface_spheres -probe_radius 1.5 < tryp_ben_ligand.xml > ligand_surface.xml
command inside_points -spheres tryp_ben_ligand.xml -surface ligand_surface.xml -egrid ligand2.dx > ligand_inside.xml
command hydro_params < ligand_inside.xml > ligand_hydro_params.xml
command test_charges < tryp_ben_ligand.xml > ligand_charges.xml
command lumped_charges -pts ligand_charges.xml > ligand_cheby.xml
command make_surface_sphere_list -surface ligand_surface.xml -spheres tryp_ben_ligand.xml -rxn rxns.xml -group ligand -core ligand > ligand_surface_atoms.xml
command mpole_grid_fit -dx ligand0.dx -solvdi 78 -debye 8.75563 > ligand_mpole.xml
command born_integral -in ligand_inside.xml -oeps 78 -debye 8.75563 -ieps 4.000000 > ligand_born.dx
command compute_charges_squared < ligand_charges.xml > ligand_charges_squared.xml
command lumped_charges -pts ligand_charges_squared.xml > ligand_squared_cheby.xml

**Comment by lvotapka** [comment]
Yes, BD simulations are run with the "any" or "any_bd" argument to run.py. If you only want to run MD, then you can either set the run.py instruction to "any_md", set the instruction to an integer (to do just one anchor), or remove the <browndye_settings_input> tag from your input XML file before running prepare.py. 

The length of time a BD simulation will run depends on the size of the system, the specific settings, and the number of available CPUs. Using the default settings on trypsin-benzamidine, and assuming your computer has 6 cores (because it's possible to have more threads than cores, which will reduce the calculation efficiency), it is likely to run for 12-24 hours or so if the "num_b_surfaces_trajectories" is set to 1,000,000.

You are correct, the MD and BD stages are independent of one another, so you can run them in any order. If you want to run them at the same time, you'd use a command like this:

```
python3.8 /home/exx/Downloads/seekr2/seekr2/run.py any_bd model.xml &
python3.8 /home/exx/Downloads/seekr2/seekr2/run.py any_md model.xml -t 500000 &
wait
```

The output looks fine to me, but are you certain that this is the entire output? There doesn't seem to be the step where the BD is actually simulated in the lines you posted.

**Comment by vaibhavadixit** [comment]
Thanks for clarifying the usage. 
Yes, the output has not changed since last night and thus I suspect if the BD is running properly or not?
Can you suggest a quick method to check the same? Like which files in anchor folders I should inspect?

Another query is related to BD and MD independence.  How does SEEKR ensure that the MD trajectories starting at the protein surface are the ones taken from BD trajectories finishing at the protein surface? Or it is that these coordinates for MD are created using probability distribution based on anchor distance from the center of the active site, thus assuming that sufficient sampling and a large number of trajectories will cancel out any influence of the choice of the starting structure.  I realize that this will be covered in the papers, but nonetheless, just wanted to confirm from you to cover any aspect that I might have missed.

Looking forward to your valuable comments and suggestions.
thank you and best regards

**Comment by lvotapka** [comment]
I'm pretty sure that if you still see the same output by now, the program is not working and it's hanging for some reason, but if you want to check whether the BD is running or has already run, then you can look inside b_surface/ and see if results.xml file exists. If it's hanging, you should probably kill the process and try again.

To answer your second question, the BD encounters with the milestones do not affect the MD starting coordinates, they are obtained independently. Typically, the MD starting coordinates are found using steered molecular dynamics where the system is slowly pulled across all milestoning surfaces until adequate starting structures have been found. Indeed with sufficient sampling and a large number of trajectories, any differences between BD and MD milestone distributions should diminish.

**Comment by vaibhavadixit** [comment]
Hi,
I noticed that the job has finished, probably in the last 2-3 hours when I was in a lecture.
New lines have been added to the output (at the bottom) and the results.xml file reads the following.
Strangely enough, the new lines did not appear while the nam_simulation process was running as shown by top command, don't know why?

Then I just ran the converge.py command which shows that the MD has not converged.
Should I try to run MD for 10, 20, 30, or 50 ns or longer MD is necessary for this system to converge?
I think the program is working fine, nonetheless, I think it's always better to check if one is able to reproduce published results before trying newer (challenging) systems which can be expected to be additionally tricky to run, analyze and interpret. Thus I want to ensure that I understand the trypsin-benzamidine system as thoroughly as possible.
Thanks a lot for your help and continued suggestions and support in this.
Best regards

(SEEKR) [exx@c107739 trypsin-benzamidine]$ cat results.xml
<rates>
<solvent>
<kT> 1 </kT>
<debye_length> 8.75563 </debye_length>
<dielectric> 78 </dielectric>
<vacuum_permittivity> 0.000142 </vacuum_permittivity>
<water_viscosity> 0.243 </water_viscosity>
<relative_viscosity> 1 </relative_viscosity>
</solvent>
<hydrodynamic_interactions> 1 </hydrodynamic_interactions>
<time_step_tolerances>
<minimum_core_dt> 0.2 </minimum_core_dt>
<minimum_core_rxn_dt> 0.05 </minimum_core_rxn_dt>
<minimum_chain_dt> 0 </minimum_chain_dt>
<minimum_chain_rxn_dt> 0 </minimum_chain_rxn_dt>
</time_step_tolerances>
<molecule_info>
<b_radius> 44.6722 </b_radius>
<b_reaction_rate> 25.4131 </b_reaction_rate>
<n_reactions> 2 </n_reactions>
</molecule_info>
<reactions>
<n_trajectories> 1000000 </n_trajectories>
<stuck> 0 </stuck>
<escaped> 956121 </escaped>
<completed>
<name> b_10 </name>
<n> 74922 </n>
</completed>
<completed>
<name> 10_9 </name>
<n> 43879 </n>
</completed>
</reactions>
<n_bd_steps> 6098052991</n_bd_steps>
</rates>

Newer lines the runstep-output.log file
BrownDye 2.0: Version of 21 Jul 2021
anchor 0 has not run the minimum number of steps 0 of 500000
anchor 1 has not run the minimum number of steps 0 of 500000
anchor 2 has not run the minimum number of steps 0 of 500000
anchor 3 has not run the minimum number of steps 0 of 500000
anchor 4 has not run the minimum number of steps 0 of 500000
anchor 5 has not run the minimum number of steps 0 of 500000
anchor 6 has not run the minimum number of steps 0 of 500000
anchor 7 has not run the minimum number of steps 0 of 500000
anchor 8 has not run the minimum number of steps 0 of 500000
anchor 9 has not run the minimum number of steps 0 of 500000
anchor 10 has not run the minimum number of steps 0 of 500000
running anchor_index: 0 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 299.3905740462872
running anchor_index: 1 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 290.271211059492
running anchor_index: 2 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 290.57912938788735
running anchor_index: 3 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 289.9179632454387
running anchor_index: 4 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 288.2288217959087
running anchor_index: 5 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 289.8268819264121
running anchor_index: 6 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 289.1137893101443
running anchor_index: 7 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 287.2416718889688
running anchor_index: 8 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 278.39734275404123
running anchor_index: 9 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 287.3503240742626
running anchor_index: 10 restart: False total_simulation_length: 500000 num_transitions: 0
Benchmark (ns/day): 287.7612200933513
running BD: b_surface restart: False trajectories to run: 1000000 transitions so far: 0
moving to directory: /home/exx/Documents/seekr-tutorial/trypsin-benzamidine/b_surface
running command: bd_top input.xml
moving to directory: /home/exx/Documents/seekr-tutorial/trypsin-benzamidine/b_surface
running command: nam_simulation receptor_ligand_simulation.xml

(SEEKR) [exx@c107739 trypsin-benzamidine]$ python3.8 /home/exx/Downloads/seekr2/seekr2/converge.py model.xml > convergestep-output.log &
converge.py output
All available options for --k_on_state include: [0]
No BD milestone has been provided for k_on_state. The BD milestone 0 has been chosen by default.
Processing interval 0 of 100
Processing interval 10 of 100
Processing interval 20 of 100
Processing interval 30 of 100
Processing interval 40 of 100
Processing interval 50 of 100
Processing interval 60 of 100
Processing interval 70 of 100
Processing interval 80 of 100
Processing interval 90 of 100
All plots have been saved to: /home/exx/Documents/seekr-tutorial/trypsin-benzamidine/images_and_plots/
Molecular dynamics results:
 - Anchor 0: 
     Milestone transitions: 0->0 : 4140, 
     Milestone avg. transition time (ps): (0, 0) : 0.241,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 1: 
     Milestone transitions: 1->0 : 2, 0->1 : 2, 
     Milestone avg. transition time (ps): 1 : 261.147, 0 : 2.155,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 2: 
     Milestone transitions: 2->1 : 27, 1->2 : 26, 
     Milestone avg. transition time (ps): 2 : 14.996, 1 : 21.813,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 3: 
     Milestone transitions: 2->3 : 2, 3->2 : 2, 
     Milestone avg. transition time (ps): 2 : 362.704, 3 : 0.514,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 4: 
     Milestone transitions: 4->3 : 3, 3->4 : 2, 
     Milestone avg. transition time (ps): 4 : 180.285, 3 : 147.377,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 5: 
     Milestone transitions: 5->4 : 1, 4->5 : 1, 
     Milestone avg. transition time (ps): 5 : 191.192, 4 : 8.832,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 6: 
     Milestone transitions: 5->6 : 5, 6->5 : 5, 
     Milestone avg. transition time (ps): 5 : 161.487, 6 : 24.467,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 7: 
     Milestone transitions: 7->6 : 3, 6->7 : 3, 
     Milestone avg. transition time (ps): 7 : 81.874, 6 : 132.827,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 8: 
     Milestone transitions: 7->8 : 7, 8->7 : 6, 
     Milestone avg. transition time (ps): 7 : 86.011, 8 : 54.058,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 9: 
     Milestone transitions: 9->8 : 8, 8->9 : 7, 
     Milestone avg. transition time (ps): 9 : 12.093, 8 : 98.255,
     Convergence value: 1.0000e+99. 
     Converged? False
 - Anchor 10: 
     Milestone transitions: 9->10 : 7, 10->9 : 7, 
     Milestone avg. transition time (ps): 9 : 122.200, 10 : 19.014,
     Convergence value: 1.0000e+99. 
     Converged? False
Brownian dynamics results:
 - b-surface reaction counts:
     to milestone 10: 74922
     to milestone 9: 43879
     to escaped: 956121
     to stuck: 0
 - BD milestone 0 reaction counts:
     to milestone 9: 43879
     to escaped: 31043

**Comment by lvotapka** [comment]
Hey that's good news that it finished. I hadn't seen the line

BrownDye 2.0: Version of 21 Jul 2021

In your previous output, so I didn't think that Browndye was running correctly. 

And yes, it looks like you're only getting 2-5 transitions for most anchors, which is probably too few to obtain meaningful results. Ideally, you would want more than 100 per anchor. So either more simulation is needed, or you would need to space your anchors together more closely. Now that you've shown that trypsin-benzamidine works, you can increase the simulation time back to the original 500 ns, if you want, (or any amount of time).

And yes, I'm happy to help. I'm going to close this issue, but feel free to respond again here and I will see it.

**Comment by vaibhavadixit** [comment]
Just to confirm if I run -t 5000000, then it would run for 10 ns, and -t 50000000 would give 100 ns, right?
But I think as you said its better to space the anchor closely because,
On my single GPU, I'm getting ~150-200 ns/day for a system of this size (approx 200 AA).
These are approximate numbers for Amber18 simulations, I have little experience with openmm to make a guess about the same here.

Thus if my understanding is correct, I should modify the input_trp_ben_mmvt.xml file to change the anchor radius values to something like 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00, 1.10, 1.20
Please do let me know if these choices for anchor radius are likely to achieve convergence with 10-20 ns MD?
thanks

**Comment by lvotapka** [comment]
Yes 5,000,000 steps is 10 ns because if you look in the input XML file and find the <timestep> tag, you can see the time per step in units of ps.

The anchor locations you suggest could work, however, you probably ought to extend out to at least 1.80 nm because the last milestone needs to extend far enough out into the solvent that the BD simulation doesn't have trouble touching the surface. Also, your k-off will be inaccurate if the final surface is too close.

10-20 ns of MD simulation per anchor are probably OK for testing and very rough approximations of kinetics/thermodynamics, but in my experience, more MD is needed per anchor to get accurate results. For instance, in our recent manuscript, we ran 500 ns per anchor for trypsin-benzamidine and 50 ns per anchor for each anchor in the host-guest system (beta-cyclodextrin with various small organic molecules).

**Comment by vaibhavadixit** [comment]
Ok, this means that for larger systems much longer MD would be required
like hundreds of ns to tens of us for systems with 500 or more AA. This
implies that GPU cluster is a must for the calculations to finish in
realistic times. A min of 4 GPU system or more.
I have setup a meeting on 20th with a Google representative to discuss the
feasibility and cost factors to avail their cloud service. Let me know if
you want to join the meeting, I can adjust the time accordingly.
Thanks and regards.

**Comment by lvotapka** [comment]
Yes, I believe you are correct.

That sounds like a great opportunity to dramatically increase your computing power. Unfortunately, I'm afraid that I will have to politely decline your offer to attend the meeting with the Google representative, but one of my colleagues, @anandojha, expressed interest to perhaps be involved with some of your processes. I'll shortly connect you both by email.

I'm also available to help with any further questions or technical assistance as problems arise.
