### ISSUE TITLE
errors in seekr2 test

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#13]
Dear Seekr2 team,
I finally got access to a GPU in my new location and tried to install seekr2, but I'm getting the following failed, error and warning messages in the testing phase.  The installation seems to have been completed without a noticeable error or major warnning. 

It seems like some input files were not found in the expected location.
Please point me to a location where these might be available so that I can copy and try to rerun these tests.
Since it has been almost a year since I last tried seekr2, I may have forgotten something that you told me earlier.

Please have a look and suggest if I can proceed with the trypsin-benzamidine tutorial?
Thank you and best regards,
Vaibhav

seekr2/tests/test_run.py::test_run_planar
  /home/niperg/Downloads/seekr2/seekr2/modules/check.py:239: UserWarning: Empty mmvt trajectories were found in anchor: 1.
    warnings.warn("Empty mmvt trajectories were found in "\

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================================== short test summary info =====================================================================================
FAILED seekr2/tests/test_common_analyze.py::test_browndye_run_compute_rate_constant - subprocess.CalledProcessError: Command 'compute_rate_constant < /home/niperg/Downloads/seekr2/seekr2/tests...
FAILED seekr2/tests/test_common_prepare.py::test_move_add_delete_input_anchors - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
FAILED seekr2/tests/test_common_prepare.py::test_modify_model - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
FAILED seekr2/tests/test_common_sim_browndye2.py::test_make_and_run_apbs - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
FAILED seekr2/tests/test_run.py::test_choose_next_simulation_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_run.py::test_normal_run_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_run.py::test_normal_restart_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_runner_namd.py::test_cleanse_anchor_outputs - AssertionError: Problem occurred running namd: results file(s) was not generated.
ERROR seekr2/tests/test_common_analyze.py::test_Data_sample_parse_browndye_results - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_base.py::test_model_get_type - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_base.py::test_model_get_timestep - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_converge.py::test_analyze_bd_only - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_cv.py::test_assign_state_points_hostguest - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_sim_openmm.py::test_create_openmm_system - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_common_sim_openmm.py::test_add_platform_cuda - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_converge.py::test_converge_default_bd_only_mmvt - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_converge.py::test_converge_default_bd_only_elber - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_elber_base.py::test_create_elber_model - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_elber_sim_openmm.py::test_elber_sim_openmm_amber - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_id_from_alias - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_alias_from_id - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_alias_from_neighbor_id - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_get_ids - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_base.py::test_check_openmm_context_within_boundary - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_sim_openmm.py::test_mmvt_sim_openmm_amber - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_mmvt_sim_openmm.py::test_check_if_state_in_anchor - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_run.py::test_choose_next_simulation_browndye2 - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_browndye2.py::test_make_browndye_input_xml - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_browndye2.py::test_make_browndye_reaction_xml - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_browndye2.py::test_modify_variables - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_browndye2.py::test_runner_browndye2_b_surface_mmvt - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_browndye2.py::test_runner_browndye2_b_surface_elber - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_namd.py::test_search_for_state_to_load - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_default - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_load_state - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_save_states - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_save_states_until_all_bounds - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_saveCheckpoint - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_default - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_default_cuda - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_load_state - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_elber - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_save_states - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_save_states_until_all_bounds - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
ERROR seekr2/tests/test_runner_openmm.py::test_mmvt_swarm - AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in
========================================================== 8 failed, 117 passed, 4 skipped, 18 warnings, 37 errors in 441.12s (0:07:21) ===========================================================
(base) [niperg@kaberi seekr2]$

**Comment by lvotapka** [comment]
It looks like you haven't installed APBS yet: https://www.poissonboltzmann.org/

**Comment by vaibhavadixit** [comment]
Dear Lane,
Actually, I've checked abps is already in my path. Thus I'm not sure why
it's not working in seeker.
Is it case sensitive?
Please suggest how to fix it.
Thanks & Regards

**Comment by lvotapka** [comment]
Are you sure that you've installed Browndye2, not Browndye? You need to also have your path variable containing the Browndye2 bin/ directory, so that you can run the program "make_apbs_input" from your path.

**Comment by vaibhavadixit** [comment]
It's working after adding browndyne2 in the path. I'll analyse the results
and get back to you in case of any queries. Thank you

**Comment by lvotapka** [comment]
Glad it worked.
