### ISSUE TITLE
unable to locate trypsin-benzamidine tutorial page

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#16]
Dear Seekr2 team,
I wanted to repeat the subject tutorial using the tutorial website that I used last year.
But strangely enough, I'm unable to get to the required webpage.
thus it will be really helpful if you can share the link to this tutorial which uses AmberTools to prepare prmtop/inpcrd files.
Thanks in advance and best regards.
Vaibhav

**Comment by lvotapka** [comment]
Is this the one you're looking for?

https://seekrtools.readthedocs.io/en/latest/tutorial_tryp_ben_prepare.html

It's in the Seekrtools repository: https://github.com/seekrcentral/seekrtools.git

**Comment by vaibhavadixit** [comment]
Yes, thanks for sharing.
I'll give my comments about your response to utility of seekr methodology
in drug design sometime soon. Thank you for bringing out some valuable
points there as well.
Thank you and best regards

**Comment by lvotapka** [comment]
Sounds good, and you're welcome.
