### ISSUE TITLE
error while generating trypsin-benzamidine smd input for hidr

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#18]
Dear Seekr2 team,
I installed seekr2 on a new system with A4000 GPU card.
While trying the tryp-benz tutorial, I'm getting the following error.
I think I've openmm latest version installed correctly via conda, even then it is giving me the following error.
Can you please suggest how to fix the same?
thank you and best regards.
Vaibhav

(base) [niperg@kaberi tryp_ben_hidr_tutorial]$ python /home/niperg/Downloads/seekrtools-master/seekrtools/hidr/hidr.py any model.xml -M SMD -p tryp_ben.pdb 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Assigning pdb file tryp_ben.pdb to anchor 0
The following procedure will be executed:
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 0 to anchor 1
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 1 to anchor 2
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 2 to anchor 3
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 3 to anchor 4
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 4 to anchor 5
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 5 to anchor 6
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 6 to anchor 7
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 7 to anchor 8
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 8 to anchor 9
SMD force constant is 90000.0 kJ/(nm**2 mol)
SMD from anchor 9 to anchor 10
Estimated total simulation time: 165.000 ns
running SMD from anchor 0 to anchor 1
running_window: (0.00865611727496281,) steps_in_window: 706719
running_window: (0.022790505547466526,) steps_in_window: 706719
running_window: (0.036924893819970245,) steps_in_window: 706719
running_window: (0.05105928209247396,) steps_in_window: 706719
running_window: (0.06519367036497767,) steps_in_window: 706719
running_window: (0.07932805863748138,) steps_in_window: 706719
running_window: (0.0934624469099851,) steps_in_window: 706719
running_window: (0.10759683518248882,) steps_in_window: 706719
running_window: (0.12173122345499253,) steps_in_window: 706719
running_window: (0.13586561172749625,) steps_in_window: 706719
running_window: (0.14999999999999997,) steps_in_window: 706719
Benchmark: 0.0 ns/day
Traceback (most recent call last):
  File "/home/niperg/Downloads/seekrtools-master/seekrtools/hidr/hidr.py", line 366, in <module>
    hidr(model, destination, pdb_files, dry_run, equilibration_steps, 
  File "/home/niperg/Downloads/seekrtools-master/seekrtools/hidr/hidr.py", line 190, in hidr
    hidr_simulation.run_SMD_simulation(
  File "/home/niperg/miniconda3/lib/python3.8/site-packages/seekrtools-0+unknown-py3.8.egg/seekrtools/hidr/hidr_simulation.py", line 534, in run_SMD_simulation
    parm = parmed.openmm.load_topology(topology, system)
  File "/home/software/amber22/lib/python3.9/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed

**Comment by vaibhavadixit** [comment]
Following is the output to show that openmm is installed and can be imported in python3.8, thus not sure why the hidr.py script fails to import it. please do suggest. thank you.

(base) [niperg@kaberi ~]$ python3.8
\Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openmm
>>>
>>> help(openmm)


Help on package openmm:

NAME
    openmm

DESCRIPTION
    OpenMM is a toolkit for molecular simulation. It can be used either as a
    stand-alone application for running simulations, or as a library you call
    from your own code. It provides a combination of extreme flexibility
    (through custom forces and integrators), openness, and high performance
    (especially on recent GPUs) that make it truly unique among simulation codes.

PACKAGE CONTENTS
    _openmm
    amd
    app (package)
    mtsintegrator
    openmm
    testInstallation
    unit (package)
    vec3
    version

CLASSES
    builtins.Exception(builtins.BaseException)
        OpenMMException
   
    class OpenMMException(builtins.Exception)
     |  This is the class used for all exceptions thrown by the C++ library.
     |  
     |  Method resolution order:
     |      OpenMMException
     |      builtins.Exception
     |      builtins.BaseException

**Comment by vaibhavadixit** [comment]
I think, I understood the problem and will post the solution if it works.

**Comment by lvotapka** [comment]
I've encountered this problem before, and it's actually a bug in Parmed. You might try upgrading parmed:

```pip install --upgrade parmed```

However, when I first encountered this problem, I had to go into the /path/to/parmed/utils/decorators.py script and delete that line that raises the ImportError. 

If you find another solution, we would be interested to hear it here.

**Comment by vaibhavadixit** [comment]
Upgrading the parmed fixed this problem.
But I'm getting errors with other AmberTools like MCBP.py and pdb4amber which are showing import error with parmed.
I've asked my student to post this error on the Amber forum, but it would be helpful if you can comment or share your experience with the same.
Thank you.
Vaibhav

**Comment by lvotapka** [comment]
I don't often use MCBP.py or pdb4amber, but one idea would be to create two separate conda envs, one that has the modified parmed for SEEKR2, and the other which has the version of parmed you need for MCBP.py and pdb4amber, if its the conflicting versions that are causing the problem.

**Comment by lvotapka** [comment]
Hi @vaibhavadixit, did this error ultimately get resolved?
