### ISSUE TITLE
seekr2 testing error on HPC

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#20]
Dear Lane,
I'm now trying to install seekr2 on an HPC system and I followed the recommended procedure to create an environment, then install seekr2_openmm_plugin using python3.8.
The installation step went well, but in the testing phase, I'm getting the following error.
Where can I get the seekr2plugin? I couldn't find a page, conda or git command for the same.
Please suggest how to fix this.
Thank you and best regards.

(myseekr2) [root@node1 software]# cd seekr2
(myseekr2) [root@node1 seekr2]# python setup.py test
/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
running pytest
running egg_info
writing seekr2.egg-info/PKG-INFO
writing dependency_links to seekr2.egg-info/dependency_links.txt
writing requirements to seekr2.egg-info/requires.txt
writing top-level names to seekr2.egg-info/top_level.txt
reading manifest file 'seekr2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
adding license file 'LICENSE'
writing manifest file 'seekr2.egg-info/SOURCES.txt'
running build_ext
=========================================================== test session starts ============================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/software/seekr2
collecting ... Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
collected 0 items / 1 error                                                                                                                

================================================================== ERRORS ==================================================================
______________________________________________________ ERROR collecting test session _______________________________________________________
../miniconda3/envs/myseekr2/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../miniconda3/envs/myseekr2/lib/python3.8/site-packages/pytest-7.1.2-py3.8.egg/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
seekr2/tests/conftest.py:13: in <module>
    import seekr2.prepare as prepare
seekr2/prepare.py:15: in <module>
    import seekr2.modules.check as check
seekr2/modules/check.py:59: in <module>
    import seekr2.modules.mmvt_sim_openmm as mmvt_sim_openmm
seekr2/modules/mmvt_sim_openmm.py:18: in <module>
    import seekr2plugin
E   ModuleNotFoundError: No module named 'seekr2plugin'
========================================================= short test summary info ==========================================================
ERROR  - ModuleNotFoundError: No module named 'seekr2plugin'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================= 1 error in 0.94s =============================================================

**Comment by lvotapka** [comment]
Does seekr2plugin appear when you enter "conda list"?

**Comment by lvotapka** [comment]
Because seekr2plugin is a part of seekr2_openmm_plugin.

**Comment by vaibhavadixit** [comment]
conda list shows that both seekr2 and the plugin are available.
Please suggest what change I should make to avoid errors in testing.
thanks.

(myseekr2) [root@node1 seekr2]# conda list | grep seekr
# packages in environment at /home/software/miniconda3/envs/myseekr2:
seekr2                    0+untagged.239.gcaa21a8          pypi_0    pypi
seekr2_openmm_plugin      0.1.4            py38h7af0aa8_1    conda-forge
(myseekr2) [root@node1 seekr2]#

**Comment by lvotapka** [comment]
What happens if you open python in a terminal and type:

```
import seekr2plugin
```
?

**Comment by vaibhavadixit** [comment]
This is what I'm getting.

myseekr2) [root@node1 ~]# python
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import seekr2plugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'seekr2plugin'
>>>

**Comment by lvotapka** [comment]
I'm not sure why conda shows it installed, but python won't import it. What OS are you using?

**Comment by vaibhavadixit** [comment]
os centos stream 8

**Comment by lvotapka** [comment]
Yeah SEEKR2 always seems to have trouble with CentOS. 

I would suggest trying again to install SEEKR2 and Seekr2_openmm_plugin from CondaForge on a fresh conda environment, preferably interactively on one of the nodes it will run on, and try to follow the installation instructions exactly.

If that doesn't work, you'll probably need to install the seekr2_openmm_plugin from source by following the instructions here: https://seekr2.readthedocs.io/en/latest/installation.html

**Comment by vaibhavadixit** [comment]
OK, I'll try these options with the help of HPC installation team and get back in case we need more inputs/help from you. thank you

**Comment by lvotapka** [comment]
Good luck. I'm here to help if I can.

**Comment by ratanrabha** [comment]
Greetings!
We have followed the guide you have provided and install openmm from source
Got following error at the end of seekr2 installation:

error: numpy 1.23.1 is installed but numpy<1.23.0,>=1.16.5 is required by {'scipy'}


Also following error during testing phase:

============================================= test session starts ==============================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/software/seekr2
collecting ... Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
collected 0 items / 1 error                                                                                    

==================================================== ERRORS ====================================================
________________________________________ ERROR collecting test session _________________________________________
__init__.pxd:942: in numpy.import_array
    ???
E   RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:
../miniconda3/envs/envseekr2/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../miniconda3/envs/envseekr2/lib/python3.8/site-packages/pytest-7.1.2-py3.8.egg/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
seekr2/tests/conftest.py:13: in <module>
    import seekr2.prepare as prepare
seekr2/prepare.py:13: in <module>
    import seekr2.modules.common_prepare as common_prepare
seekr2/modules/common_prepare.py:17: in <module>
    import seekr2.modules.mmvt_base as mmvt_base
seekr2/modules/mmvt_base.py:14: in <module>
    import mdtraj
../miniconda3/envs/envseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/__init__.py:30: in <module>
    from .formats.registry import FormatRegistry
../miniconda3/envs/envseekr2/lib/python3.8/site-packages/mdtraj-1.9.7-py3.8-linux-x86_64.egg/mdtraj/formats/__init__.py:4: in <module>
    from .dcd import DCDTrajectoryFile
mdtraj/formats/dcd/dcd.pyx:32: in init mdtraj.formats.dcd
    ???
__init__.pxd:944: in numpy.import_array
    ???
E   ImportError: numpy.core.multiarray failed to import
=============================================== warnings summary ===============================================
../miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:229
  /home/software/miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:229: DeprecationWarning: invalid escape sequence \.
    elif re.search('[\.]', val.text):

../miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:254
  /home/software/miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:254: DeprecationWarning: invalid escape sequence \.
    elif re.search('[\.]', val):

../miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:293
  /home/software/miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:293: DeprecationWarning: invalid escape sequence \S
    '[0-9]?\S*[A-Za-z]\S*|'

../miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:294
  /home/software/miniconda3/envs/envseekr2/lib/python3.8/site-packages/abserdes-2.8-py3.8.egg/abserdes/strcast.py:294: DeprecationWarning: invalid escape sequence \.
    '-?\.?\d+\.?\d*|\d+',

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================================== short test summary info ============================================
ERROR  - ImportError: numpy.core.multiarray failed to import
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 4 warnings, 1 error in 2.69s =========================================
(envseekr2) [root@node1 seekr2]#

**Comment by lvotapka** [comment]
It looks like there's a problem with the numpy version. Maybe try installing a different version:

```
conda install numpy=x.x.x
```
Is there a way to recreate this error without running SEEKR2? Like can you just import numpy or mdtraj in python to get this error?

**Comment by ratanrabha** [comment]
Greetings!!
This is how we followed to install seekr2. We could finally execute the "python setup.py test" . However, there are few error/failed logs during test phase. Is the resulted error/failed logs are good to go to run our jobs?. We have not installed namd and it seems most of the error are related to namd. Please advice. 

Thank you! 

Installation directory "/home/software/"


Step1: Installed Miniconda3 in /home/software/miniconda3 directory
***************************************************************
Step2: Create and activate conda environment
#conda create --name myseekr2 python=3.8
#conda activate myseekr2
********************************************************
Step 3: Installation of Browndyn2
-> Installed dependencies for centos 8
#dnf group install "Development Tools"
#dnf install ocaml expat-devel lapack-devel
Then :
#tar xvfz browndye2.tar.gz
#cd browndye2
#make -j 4 all

Path is specified in /etc/bashrc

export PATH=$PATH:/usr/local/cuda-11.6/bin:home/software/browndye2/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.6/lib64

**************************************************************************************
Step 4: Installation of Openmm from source
Installed dependencies first
#conda install netcdf4 mpi4py swig
#pip install numpy scipy
#conda install -c conda-forge doxygen
#pip install --upgrade cython

#git clone https://github.com/openmm/openmm.git
#cd openmm
#mkdir build
#cd build
#ccmake ..
#make
#make install
#make PythonInstall

Openmm path is also specified in /etc/bashrc [openmm is installed in /home/software/openmm1 ]

export PATH=$PATH:/usr/local/cuda-11.6/bin:/home/software/browndye2/bin:/home/software/openmm1/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.6/lib64:/home/software/openmm1/lib

*****************************************************************************************
Step 5: Installed the SEEKR2 Plugin on top of this version of OpenMM:

#cd to another directory
#git clone https://github.com/seekrcentral/seekr2_openmm_plugin.git
#cd seekr2_openmm_plugin/seekr2plugin
#mkdir build
#cd build
#ccmake ..
#make
#make install
#make PythonInstall
**************************************************************
Step 6: Installation of SEEKR2

#git clone https://github.com/seekrcentral/seekr2.git
#cd seekr2
#python setup.py install

Installation done without error
**********************************************************
Step 7: Seekr2 test
#python setup.py test
*************************************************************


We did not installed NAMD as this is optional and we have installed openmm
Testing done but following error have occured.

============================================================== short test summary info ===============================================================
FAILED seekr2/tests/test_common_prepare.py::test_move_add_delete_input_anchors - AssertionError: Problem running run_apbs_input - APBS DX file(s) n...
FAILED seekr2/tests/test_common_prepare.py::test_modify_model - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: recepto...
FAILED seekr2/tests/test_common_sim_browndye2.py::test_make_and_run_apbs - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fou...
FAILED seekr2/tests/test_run.py::test_choose_next_simulation_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_run.py::test_normal_run_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_run.py::test_normal_restart_namd - AssertionError: Problem occurred running namd: results file(s) was not generated.
FAILED seekr2/tests/test_runner_namd.py::test_cleanse_anchor_outputs - AssertionError: Problem occurred running namd: results file(s) was not gener...
ERROR seekr2/tests/test_common_analyze.py::test_Data_sample_parse_browndye_results - AssertionError: Problem running run_apbs_input - APBS DX file(...
ERROR seekr2/tests/test_common_base.py::test_model_get_type - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: receptor*.dx
ERROR seekr2/tests/test_common_base.py::test_model_get_timestep - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: recep...
ERROR seekr2/tests/test_common_base.py::test_model_get_bulk_index - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: rec...
ERROR seekr2/tests/test_common_converge.py::test_analyze_bd_only - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: rece...
ERROR seekr2/tests/test_common_cv.py::test_assign_state_points_hostguest - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fou...
ERROR seekr2/tests/test_common_sim_openmm.py::test_create_openmm_system - AssertionError: Problem running run_apbs_input - APBS DX file(s) not foun...
ERROR seekr2/tests/test_common_sim_openmm.py::test_add_platform_cuda - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: ...
ERROR seekr2/tests/test_converge.py::test_converge_default_bd_only_mmvt - AssertionError: Problem running run_apbs_input - APBS DX file(s) not foun...
ERROR seekr2/tests/test_converge.py::test_converge_default_bd_only_elber - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fou...
ERROR seekr2/tests/test_elber_base.py::test_create_elber_model - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: recept...
ERROR seekr2/tests/test_elber_sim_openmm.py::test_elber_sim_openmm_amber - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fou...
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_id_from_alias - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: ...
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_alias_from_id - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: ...
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_alias_from_neighbor_id - AssertionError: Problem running run_apbs_input - APBS DX file(s) no...
ERROR seekr2/tests/test_mmvt_base.py::test_MMVT_anchor_get_ids - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: recept...
ERROR seekr2/tests/test_mmvt_base.py::test_check_openmm_context_within_boundary - AssertionError: Problem running run_apbs_input - APBS DX file(s) ...
ERROR seekr2/tests/test_mmvt_sim_openmm.py::test_mmvt_sim_openmm_amber - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found...
ERROR seekr2/tests/test_mmvt_sim_openmm.py::test_check_if_state_in_anchor - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fo...
ERROR seekr2/tests/test_run.py::test_choose_next_simulation_browndye2 - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found:...
ERROR seekr2/tests/test_run.py::test_get_current_step_openmm_state - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: re...
ERROR seekr2/tests/test_run.py::test_run_load_state - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: receptor*.dx
ERROR seekr2/tests/test_runner_browndye2.py::test_make_browndye_input_xml - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fo...
ERROR seekr2/tests/test_runner_browndye2.py::test_make_browndye_reaction_xml - AssertionError: Problem running run_apbs_input - APBS DX file(s) not...
ERROR seekr2/tests/test_runner_browndye2.py::test_modify_variables - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: re...
ERROR seekr2/tests/test_runner_browndye2.py::test_runner_browndye2_b_surface_mmvt - AssertionError: Problem running run_apbs_input - APBS DX file(s...
ERROR seekr2/tests/test_runner_browndye2.py::test_runner_browndye2_b_surface_elber - AssertionError: Problem running run_apbs_input - APBS DX file(...
ERROR seekr2/tests/test_runner_namd.py::test_search_for_state_to_load - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found:...
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_default - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: rece...
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_load_state - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: r...
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_save_states - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: ...
ERROR seekr2/tests/test_runner_namd.py::test_Runner_namd_save_states_until_all_bounds - AssertionError: Problem running run_apbs_input - APBS DX fi...
ERROR seekr2/tests/test_runner_openmm.py::test_saveCheckpoint - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: recepto...
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_default - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: ...
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_default_cuda - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fo...
ERROR seekr2/tests/test_runner_openmm.py::test_Runner_openmm_load_state - AssertionError: Problem running run_apbs_input - APBS DX file(s) not foun...
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_elber - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: re...
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_save_states - AssertionError: Problem running run_apbs_input - APBS DX file(s) not fou...
ERROR seekr2/tests/test_runner_openmm.py::test_runner_openmm_save_states_until_all_bounds - AssertionError: Problem running run_apbs_input - APBS D...
ERROR seekr2/tests/test_runner_openmm.py::test_mmvt_swarm - AssertionError: Problem running run_apbs_input - APBS DX file(s) not found: receptor*.dx
==================================== 7 failed, 120 passed, 4 skipped, 3 warnings, 40 errors in 371.01s (0:06:11) =====================================

**Comment by lvotapka** [comment]
Ah yes it looks like you’ve successfully installed almost everything, and the remaining errors are because NAMD and APBS are missing. If you’ll be using OpenMM (recommended) then you won’t need NAMD, and you’ll only need APBS if you’re planning to use this platform to run Brownian dynamics.

**Comment by ratanrabha** [comment]
Hello Ivotapka!
We appreciate and thank you for your help in this regards.

Finally completed installation and testing on Centos Stream 8. Test phase done with few warnings and no error. 

(APBS installed)

**Comment by lvotapka** [comment]
Great to hear!
