### ISSUE TITLE
error setting up seekr2 calculation with Heme protein

### ISSUE THREAD

**Issue by vaibhavadixit** [seekrcentral/seekr2#27]
Dear Seekr2 team,
We (myself and @pulkit2907 ) have been attempting to run seekr2 on new systems (after successful training with tutorial).
We closely followed the procedure used for trypsin-benzamidine system realizing that there ought to be major differences.

Our system is oxygen bound to Heme-Fe, but we parameterized Heme without O2 bound and separately parameterized O2 in G16-antechamber.
In the 1st prepare.py step, we defined group 1 as Heme only Hydrogen atoms and Fe (which gave an error, thus removing Fe from the list).
In group 2, only two O atoms were kept.
Now we are getting the following error. regarding failure to generate apbs receptor*.in input file.
We are unable to identify any difference between the tutorial and our input html file that might be the reason for the error (diff output below).

Thus, we're requesting you to please have a look at these and suggest how to fix the same.
thank you and best regards.
Vaibhav

[jrfnsm@param_embryo 1mbo_seekr2]$ tail job.775.err
    model, xml_path = prepare(model_input, force_overwrite)
  File "/home/software/seekr2/seekr2/prepare.py", line 42, in prepare
    common_prepare.generate_bd_files(model, root_directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_prepare.py", line 961, in generate_bd_files
    runner_browndye2.make_browndye_input_xml(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_browndye2.py", line 175, in make_browndye_input_xml
    debye_length = sim_browndye2.make_and_run_apbs(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_sim_browndye2.py", line 975, in make_and_run_apbs
    assert len(glob.glob(apbs_input_glob)), "Problem running " \
AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in

[jrfnsm@param_embryo 1mbo_seekr2]$ diff input_Mb_OXY_hidr1.xml trypsin-input.xml
8c8
<     <temperature>300.0</temperature>
---
>     <temperature>298.0</temperature>
11c11
<     <root_directory>~/mb_oxy_hidr_tutorial/</root_directory>
---
>     <root_directory>/home/vaibhav/seekr2-tutorial</root_directory>
21,24c21,24
<             <group1>[438, 442, 443, 444, 691, 1050, 1052, 1099, 1100, 1103, 1104, 1105, 1749, 1750, 1751, 2499, 2500, 2528]</group1>
<             <group2>[2533, 2534]</group2>
<             <bd_group1>[438, 442, 443, 444, 691, 1050, 1052, 1099, 1100, 1103, 1104, 1105, 1749, 1750, 1751, 2499, 2500, 2528]</bd_group1>
<             <bd_group2>[0, 1]</bd_group2>
---
>             <group1>[2478, 2489, 2499, 2535, 2718, 2745, 2769, 2787, 2794, 2867, 2926]</group1>
>             <group2>[3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229]</group2>
>             <bd_group1>[2478, 2489, 2499, 2535, 2718, 2745, 2769, 2787, 2794, 2867, 2926]</bd_group1>
>             <bd_group2>[0, 1, 2, 3, 4, 5, 6, 7, 8]</bd_group2>
31c31
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
43c43
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
55c55
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
67c67
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
79c79
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
91c91
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
103c103
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
115c115
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
127c127
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
139c139
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
151c151
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
163c163
<                         <prmtop_filename>1mbo_solv_oxy.prmtop</prmtop_filename>
---
>                         <prmtop_filename>tryp_ben.prmtop</prmtop_filename>
175,176c175,176
<         <receptor_pqr_filename>mb_oxy_receptor.pqr</receptor_pqr_filename>
<         <ligand_pqr_filename>mb_oxy_ligand.pqr</ligand_pqr_filename>
---
>         <receptor_pqr_filename>tryp_ben_receptor.pqr</receptor_pqr_filename>
>         <ligand_pqr_filename>tryp_ben_ligand.pqr</ligand_pqr_filename>

**Comment by lvotapka** [comment]
Is Browndye correctly installed? Try:

```
which make_apbs_inputs
```

**Comment by vaibhavadixit** [comment]
Hi Lane,
The issue was identical to the one we faced earlier and removing the first line from pqr file allowed the apbs inputs to be created and make_apbs_inputs is running. (https://github.com/seekrcentral/seekr2/issues/23)
Nonetheless, it will be helpful if you can comment on the choice of group1 and 2 atoms.
We are still not sure if the choice of anchors is optimal since the default radius might lead to unnecessary MD-sampling in an area outside the active site where only bulk solvent is present.
Looking forward to your suggestions.
thank you and best regards.
Vaibhav

**Comment by vaibhavadixit** [comment]
the make_apbs_inputs is running since 30 mins but I"m not sure if its doing anything since b_surface directory has only the following files.
Please suggest if it is stuck somewhere (in a loop)!
input.xml file is empty.

(base) [jrfnsm@param_embryo b_surface]$ pwd
/home/jrfnsm/1mbo_seekr2/mb_oxy_hidr_tutorial/b_surface
(base) [jrfnsm@param_embryo b_surface]$ ls -arlht
total 720K
drwxrwxr-x 14 jrfnsm jrfnsm 4.0K Nov  3 22:33 ..
-rw-rw-r--  1 jrfnsm jrfnsm    0 Nov  3 22:33 input.xml
-rw-rw-r--  1 jrfnsm jrfnsm 181K Nov  4 07:42 mb_oxy_receptor.pqr
-rw-rw-r--  1 jrfnsm jrfnsm  299 Nov  4 07:42 mb_oxy_ligand.pqr
-rw-rw-r--  1 jrfnsm jrfnsm 519K Nov  4 07:42 mb_oxy_receptor.xml
-rw-rw-r--  1 jrfnsm jrfnsm  832 Nov  4 07:42 mb_oxy_ligand.xml
-rw-rw-r--  1 jrfnsm jrfnsm 1.7K Nov  4 07:42 apbs_input.xml
drwxrwxr-x  2 jrfnsm jrfnsm  177 Nov  4 08:21 .
(base) [jrfnsm@param_embryo b_surface]$


Thank you.

**Comment by vaibhavadixit** [comment]
It finished with the same error.
apbs is indeed installed in the seekr environment and is accessible as shown below.
Thus we are unable to understand the reason for this error.
Please suggest what to try next to fix this.

(base) [jrfnsm@param_embryo 1mbo_seekr2]$ tail job.800.err
    model, xml_path = prepare(model_input, force_overwrite)
  File "/home/software/seekr2/seekr2/prepare.py", line 42, in prepare
    common_prepare.generate_bd_files(model, root_directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_prepare.py", line 961, in generate_bd_files
    runner_browndye2.make_browndye_input_xml(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/runner_browndye2.py", line 175, in make_browndye_input_xml
    debye_length = sim_browndye2.make_and_run_apbs(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_sim_browndye2.py", line 975, in make_and_run_apbs
    assert len(glob.glob(apbs_input_glob)), "Problem running " \
AssertionError: Problem running make_apbs_input - APBS input files not found: receptor*.in


[jrfnsm@node1 ~]$ source /home/software/miniconda3/bin/activate
(base) [jrfnsm@node1 ~]$ conda activate myseekr2
(myseekr2) [jrfnsm@node1 ~]$ apbs --help


----------------------------------------------------------------------
    APBS -- Adaptive Poisson-Boltzmann Solver
    Version 1.5

    Nathan A. Baker (nathan.baker@pnnl.gov)
    Pacific Northwest National Laboratory

**Comment by lvotapka** [comment]
I would suggest running the individual steps within the b_surface/ folder manually to see where something is going wrong:

```
make_apbs_inputs apbs_input.xml > input.xml
run_apbs_inputs input.xml > run_apbs_input.out
```

**Comment by vaibhavadixit** [comment]
Hi,
The first command gives an error after running for some time.
Is it something wrong with the input files (pqr) or some bug in the apbs or seekr2 that is very specific to this protein?
Please suggest. thank you.

(myseekr2) [jrfnsm@node1 b_surface]$ make_apbs_inputs apbs_input.xml > input.xml
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by lvotapka** [comment]
I'm not sure what is causing this problem @vaibhavadixit, as this is a problem with the Browndye program "make_apbs_inputs". Are you using a very small resolution for the APBS grid? Is your PQR file huge? You might reach out to the Browndye developers if you can't figure out what is going wrong.

**Comment by pulkit2907** [comment]
make_apbs_inputs apbs_input.xml > input.xml
after running this commands again on a new fresh installation where newest release browndye2 is installed proprerly and tested by running its tutorial. following error is generated
**killed**

**Comment by lvotapka** [comment]
Did this problem ever get fully resolved, @vaibhavadixit  and @pulkit2907 ?

**Comment by pulkit2907** [comment]
> Did this problem ever get fully resolved, @vaibhavadixit and @pulkit2907 ?

No. I also tried after updating browndye2 and changing the grid resolution but still error is coming out. If you could help me I can share my files(prmtop pqr model.xml) for a brief look.

**Comment by lvotapka** [comment]
Why don't you just share the PQR file first and see if I can reproduce the error.

**Comment by pulkit2907** [comment]
> Why don't you just share the PQR file first and see if I can reproduce the error.

Okay i will share it tommorrow morning....it's 11 of night here and pqr files are in work station in University lab. Than you for your time.

**Comment by lvotapka** [comment]
I'm assuming the problem got resolved.
