### ISSUE TITLE
warnings in prepare.py step

### ISSUE THREAD

**Issue by pulkit2907** [seekrcentral/seekr2#28]
dear developers
i ran the try_benz tutorial in my workstataion.  while running prepare.py the following warining came. Please suggest whether  these errors can safely avoidable and does not affect the final kon, koff values to a large extent. in case of large effect please suggest the source of error and possible way to avoid these errors.
(SEEKR) cadd-sys3@caddsys3:~/Documents/seekr_tutorial$ python /home/cadd-sys3/setupfiles/seekr2/seekr2/prepare.py input_tryp_ben_hidr.xml 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
**Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!**

Vpmg_ctor2: 
Warning: External energies are not used in BCFL_MAP calculations!
MGparm_check:  you're using a very small nlev (1) and therefore
MGparm_check:  will not get the optimal performance of the multigrid

thanking you in anticipation

**Comment by lvotapka** [comment]
This is the same set of warning mentioned in https://github.com/seekrcentral/seekr2/issues/17#issuecomment-1305944283

In short, these errors are safe, and should not affect the outcomes of any SEEKR2 calculations.
