### ISSUE TITLE
Facing an issue in running seekr2 in the HIDR step on trypsin-benzamidine system

### ISSUE THREAD

**Issue by MissRaut** [seekrcentral/seekr2#30]
Hello, Janvi here. 
I am a master student at National Institute of Pharmaceutical Education & Research, Guwahati India. Working under 
Dr Vaibhav Dixit. I am using trypsin-benzamidine tutorials for seeker2 on HPC installation and I am able to generate the results till step of  constructing the SEEKR2 Model Input File. 
After generating an empty modeI I'm stuck at "Running HIDR on the new Model", job error shows 

"you should atleast have OpenMM 6.3 installed ", 

whereas my system is already having OpenMM 7.7 installed , 
what could be the remedy?

Please suggest so that I can move forward in the tutorial and then apply SEEKR2 methodology to my project work.
Thank you and Best regards.

**Comment by lvotapka** [comment]
Would you please post more information about the error: what command you were running and the full set of lines output before the error?

**Comment by MissRaut** [comment]
Yes Sir , Here is the command I were using 

"python3.8 /home/software/seekr2/seekr2/prepare.py input_tryp_ben_hidr-new.xml " for which I got " model.xml" as an output.

the another command 

"python ~/seekrtools/seekrtools/hidr/hidr.py any ~/tryp_ben_hidr_tutorial/model.xml -M SMD -p tryp_ben.pdb"
is giving following error : 

"Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 366, in <module>
    hidr(model, destination, pdb_files, dry_run, equilibration_steps,
  File "/home/software/seekrtools/seekrtools/hidr/hidr.py", line 175, in hidr
    ns_per_day = hidr_simulation.run_min_equil_anchor(
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekrtools-0+untagged.65.g549ac37-py3.8.egg/seekrtools/hidr/hidr_simulation.py", line 347, in run_min_equil_anchor
    parm = parmed.openmm.load_topology(topology, system)
  File "/home/software/amber22/lib/python3.9/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed"

**Comment by lvotapka** [comment]
In the first command, it looks like you're using python3.8, but in the second you're just using "python", which seems to be Python 3.9. Are you sure that OpenMM and the SEEKR plugin is installed in the version of Python you are using for the HIDR command?

**Comment by MissRaut** [comment]
Thank you for your hint Mr. Lane, it worked.

**Comment by lvotapka** [comment]
Excellent

**Comment by MissRaut** [comment]
Hello  Mr. Lane  Janvi here,
 I wanted to use multiple GPU Card for running my command instead of using  "any". 
 According to your previous comments on following issue  "BD or MD first with run.py any #21"  

I  tried using
" python /home/software/seekr2/seekr2/run.py 0 model.xml -f -c 0 &
  python /home/software/seekr2/seekr2/run.py 1 model.xml -f -c 1 &
  python /home/software/seekr2/seekr2/run.py 2 model.xml -f -c 2 &
  python /home/software/seekr2/seekr2/run.py 3 model.xml -f -c 3 &
  wait"

but it didn't work, also I used following command ,

" python "/home/software/seekr2new/seekr2/seekr2/run.py" any "/home/msmeity/JANVI/SEEKR/tryp_ben_hidr_tutorial3/model.xml" -f -c '1,2' &  "   which also failed .

can you please suggest  ?

**Comment by lvotapka** [comment]
Please copy this into a new issue, and post the exact error message(s).

**Comment by MissRaut** [comment]
sure sir.
