### ISSUE TITLE
How to use multiple GPU ?

### ISSUE THREAD

**Issue by MissRaut** [seekrcentral/seekr2#31]
Hello Mr. Lane Janvi here,
I wanted to use multiple GPU Card for running my command instead of using "any".
According to your previous comments on following issue "BD or MD first with run.py any https://github.com/seekrcentral/seekr2/issues/21"

I tried using
" python /home/software/seekr2/seekr2/run.py 0 model.xml -f -c 0 &
python /home/software/seekr2/seekr2/run.py 1 model.xml -f -c 1 &
python /home/software/seekr2/seekr2/run.py 2 model.xml -f -c 2 &
python /home/software/seekr2/seekr2/run.py 3 model.xml -f -c 3 &
wait"

but it didn't work, also I used following command , I am getting empty out file and error files.

" python "/home/software/seekr2new/seekr2/seekr2/run.py" any "/home/msmeity/JANVI/SEEKR/tryp_ben_hidr_tutorial3/model.xml" -f -c '1,2' & ".
  error file is empty here as well.

can you please suggest ?

**Comment by lvotapka** [comment]
I'm not sure what might be going wrong without an error or output file - I have no way to know if the issue is with SEEKR2 or an error in the submission settings.

Are these lines being used in a SLURM submission script? If so, what is the whole script? Are you sure that all 4 GPUs are available? Any way you could attempt an interactive job with 4 GPUs to test these commands directly?

**Comment by MissRaut** [comment]
Okay , Here is the Script I am using (plz ignore 4 commands in my previous comment those were sample.)

#!/bin/bash
#SBATCH -A  111               ##account name
#SBATCH -p GPU_NODES           #partition name
#SBATCH --nodes=1             ## number of nodes
#SBATCH --nodelist=node4     ###node lists
#SBATCH --ntasks-per-node=15  ## number os  processor core(s) per node
#SBATCH --time=95:50:20      ##time optional
#SBATCH --job-name=seekr      ##job name
#SBATCH --error=job.%J.err    ## any error during job submission or execution
#SBATCH --output=job.%J.out   ##any output after job execution

source /home/software/miniconda3/bin/activate
conda activate myseekr2

python3.8 "/home/software/seekr2new/seekr2/seekr2/run.py" any "/home/MS/chem/SEEKR/tryp_ben_hidr_tutorial3/model.xml" -f -c '1,2' & ".


& as you asked here is the list of nodes available on my system :- 

PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
CPU_NODES    up   infinite      2    mix node[3-4]
CPU_NODES    up   infinite      2   idle node[2,5]
GPU_NODES    up   infinite      1    mix node4
GPU_NODES    up   infinite      1   idle node1        

and here is the GPU cards available on node 4 , how can I call multiple card in one script  plz suggest,
[GPU CARD.pdf](https://github.com/seekrcentral/seekr2/files/12169887/GPU.CARD.pdf)

what are the required changes in script sir ?

**Comment by lvotapka** [comment]
The following argument actually requests the number of tasks, not cores, to use for the node. And since you'll be running 4 concurrent tasks, you'll only need to set:

```
--ntasks-per-node=4
```

Second thought: are you sure that python3.8 is where OpenMM and the seekr2_openmm_plugin are installed? If so, you might try just running one instance of run.py to see whether it will work. On that note, is it possible that something is wrong with the conda environment you are activating? Does it work on an interactive node?

It also looks like, based on your screenshot, that only 3 GPUs are available, so you cannot request a fourth device.

I would suggest using something like the following:

```
#!/bin/bash
#SBATCH -A 111 ##account name
#SBATCH -p GPU_NODES #partition name
#SBATCH --nodes=1 ## number of nodes
#SBATCH --nodelist=node4 ###node lists
#SBATCH --ntasks-per-node=4 ## number os processor core(s) per node
#SBATCH --time=95:50:20 ##time optional
#SBATCH --job-name=seekr ##job name
#SBATCH --error=job.%J.err ## any error during job submission or execution
#SBATCH --output=job.%J.out ##any output after job execution

source /home/software/miniconda3/bin/activate
conda activate myseekr2
python3.8 /home/software/seekr2/seekr2/run.py 0 model.xml -f -c 0 &
python3.8 /home/software/seekr2/seekr2/run.py 1 model.xml -f -c 1 &
python3.8 /home/software/seekr2/seekr2/run.py 2 model.xml -f -c 2 &
wait
```

You should try experimenting to see whether it works with just one of the run.py lines. Also, are you sure that the job handler lets you submit jobs that are so long (96 hours)?

But really, without any sort of error message or error/output file, I cannot tell you exactly what is going wrong.

**Comment by MissRaut** [comment]
Thank you for your precise response Mr Lane, 
 yes I am allowed to submit such longer jobs. 
I have tried submitting the job using the script suggested by you, and the error is as followed 

Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/home/software/seekr2/seekr2/run.py", line 851, in <module>
    model = base.load_model(model_file, directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_base.py", line 986, in load_model
    assert os.path.exists(model_file), \
AssertionError: A nonexistent model file was specified: model.xml.
Traceback (most recent call last):
  File "/home/software/seekr2/seekr2/run.py", line 851, in <module>
    model = base.load_model(model_file, directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_base.py", line 986, in load_model
    assert os.path.exists(model_file), \
AssertionError: A nonexistent model file was specified: model.xml.
Traceback (most recent call last):
  File "/home/software/seekr2/seekr2/run.py", line 851, in <module>
    model = base.load_model(model_file, directory)
  File "/home/software/miniconda3/envs/myseekr2/lib/python3.8/site-packages/seekr2-0+untagged.239.gcaa21a8-py3.8.egg/seekr2/modules/common_base.py", line 986, in load_model
    assert os.path.exists(model_file), \
AssertionError: A nonexistent model file was specified: model.xml.
~

**Comment by lvotapka** [comment]
OK good.

As the error message suggests, the file "model.xml" isn't being found. You need to provide an absolute path or change to the directory where the model.xml file exists.

**Comment by MissRaut** [comment]
Hello Sir , I did the required changes and submitted new job which is running now but it is only using 2 GPU card  and not 3rd one.


 NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                     Off | 00000000:31:00.0 Off |                    0 |
|  0%   90C    P0             126W / 150W |   1086MiB / 23028MiB |    ### 100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10                     Off | 00000000:4B:00.0 Off |                    0 |
|  0%   90C    P0             113W / 150W |    320MiB / 23028MiB |     ### 97%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A10                     Off | 00000000:B1:00.0 Off |                    0 |
|  0%   30C    P8              17W / 150W |      7MiB / 23028MiB |     ###  0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by lvotapka** [comment]
As long as you used the correct device indices for the "-c" argument, you should be using all three GPUs. As the script above shows, the first run.py line should have "-c 0", the second line should have "-c 1", and so on for as many GPUs as your node has.

**Comment by MissRaut** [comment]
Yes Sir, My script is having the same commands as described by you.  Initially it was using 2 GPU but today its been 3 days my script is running and now it is using 1 GPU only .  

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=============================+======================|
|   0  NVIDIA A10                     Off | 00000000:31:00.0 Off |                    0 |
|  0%   90C    P0             140W / 150W |   1086MiB / 23028MiB |    **100%**      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10                     Off | 00000000:4B:00.0 Off |                    0 |
|  0%   31C    P8              15W / 150W |      7MiB / 23028MiB |      **0%**      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A10                     Off | 00000000:B1:00.0 Off |                    0 |
|  0%   29C    P8              15W / 150W |      7MiB / 23028MiB |      **0%**      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+------------------

**Comment by lvotapka** [comment]
Ah then this is most likely because one or two of the SEEKR2 run calculations has either finished or failed with an error. The error and output files should let you know whether they succeeded or not.

**Comment by MissRaut** [comment]
Hello Mr. Lane ,
                     here is my script .......
#!/bin/bash
#SBATCH -A 111 ##account name
#SBATCH -p GPU_NODES #partition name
#SBATCH --nodes=1 ## number of nodes
#SBATCH --nodelist=node4 ###node lists
#SBATCH --ntasks-per-node=4 ## number os processor core(s) per node
#SBATCH --job-name=TASK ##job name
#SBATCH --error=job.%J.err ## any error during job submission or execution
#SBATCH --output=job.%J.out ##any output after job execution

source /home/software/miniconda3/bin/activate
conda activate myseekr2
python3.8 /home/software/seekr2/seekr2/run.py 0 /home/ms/chem/SEEKR/tryp_ben_hidr_tutorial3/model.xml -f -c 0 &
python3.8 /home/software/seekr2/seekr2/run.py 1 /home/ms/chem/SEEKR/tryp_ben_hidr_tutorial3/model.xml -f -c 1 &
python3.8 /home/software/seekr2/seekr2/run.py 2 /home/ms/chem/SEEKR/tryp_ben_hidr_tutorial3/model.xml -f -c 2 &
wait

As you said earlier there was some error in script and resubmitted the job  with correction and for few hours it was using 3 GPU but now its been (1-12:00:25 ) the job is running , but on only 1GPU . 

here the out file ....

anchor 1 has not run the minimum number of steps 0 of 125000000 in swarm index None
running anchor_index: 1 restart: False total_simulation_length: 125000000 num_transitions: 0 swarm index: None
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)"
1250000,-347514.5968784294,297.2356419715822,285.0825653656016
anchor 2 has not run the minimum number of steps 0 of 125000000 in swarm index None
running anchor_index: 2 restart: False total_simulation_length: 125000000 num_transitions: 0 swarm index: None
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)"
1250000,-347233.71250250516,299.9960344701795,285.0825653656016
2500000,-346459.4675675533,300.2013518205027,285.0825653656016
2500000,-347524.5861039893,296.36563836689817,285.0825653656016
anchor 0 has not run the minimum number of steps 0 of 125000000 in swarm index None
running anchor_index: 0 restart: False total_simulation_length: 125000000 num_transitions: 0 swarm index: None
#"Step","Potential Energy (kJ/mole)","Temperature (K)","Box Volume (nm^3)"
1250000,-347585.93409536546,295.73784614616574,285.0825653656016
3750000,-347593.7754312209,293.77165643199055,285.0825653656016
3750000,-348412.8589667403,296.92837728937894,285.0825653656016
5000000,-348269.6196691566,292.7824426684881,285.0825653656016
5000000,-347875.4983590604,296.09886300144746,285.0825653656016
2500000,-348450.47759740753,297.2828070145314,285.0825653656016
6250000,-347910.3568627648,298.8410646582233,285.0825653656016
6250000,-347094.5753024528,294.96594421414784,285.0825653656016
7500000,-348434.13291878253,294.7092001182599,285.0825653656016
7500000,-348565.2007942968,295.13351860798804,285.0825653656016
3750000,-347728.83469347144,296.7385425436711,285.0825653656016
8750000,-348343.8731010859,299.5958189771768,285.0825653656016
8750000,-347724.4981586258,296.6808086151484,285.0825653656016
10000000,-347638.330650087,297.1106673426139,285.0825653656016
10000000,-347674.2275817143,296.82045865709784,285.0825653656016
5000000,-348289.6290002386,299.11621016688997,285.0825653656016
11250000,-347526.0919062174,300.20964329265615,285.0825653656016
11250000,-348350.25402683904,300.12139369433584,285.0825653656016
12500000,-347969.1150403754,296.1598669366457,285.0825653656016
12500000,-347905.3354626745,297.3935682274112,285.0825653656016
13750000,-347400.21540580643,300.50143093521564,285.0825653656016
6250000,-347346.86440378474,300.1904111444558,285.0825653656016
13750000,-348124.30734110484,297.28079419427837,285.0825653656016
15000000,-347887.6852389993,295.8595051129936,285.0825653656016
15000000,-347705.50130990474,298.128885224733,285.0825653656016
16250000,-346659.33143933257,297.026259106569,285.0825653656016
16250000,-348987.05584462313,299.39269110241923,285.0825653656016
7500000,-348131.9561123345,297.37160785742896,285.0825653656016
"job.5690.out" 290L, 18969

Sir I am not able to understand why it is failing to use all 3 card after few hours of run.
error file is also null.

**Comment by lvotapka** [comment]
It looks to me as though the jobs are running correctly, and on the separate cards.

**Comment by MissRaut** [comment]
yes sir , actually I was using integers in the script because of which only specific anchors were running and job was getting terminated at the benchmark, fixed now , Thanks .

**Comment by lvotapka** [comment]
Very good.
