### ISSUE TITLE
OpenMM Incompatibility

### ISSUE THREAD

**Issue by xfang216** [seekrcentral/seekr2#34]
Dear SEEKR2 team,

We recently updated OpenMM to 8.0.0 and now when I tried to run SEEKR2 for simulations (preparation is fine), I get the following error:
openmm.OpenMMException: Specified a Platform for a Context which does not support all required kernels

Is this due to a incompatibility issue? 

Thank you!

**Comment by lvotapka** [comment]
Was this installed from source or from conda-forge? We've been able to successfully test OpenMM 8.0 with SEEKR2 when both are installed from source.

Are you able to run OpenMM simulations (without SEEKR2) on the CUDA platform? And are you sure that you are using either the "CUDA" or "Reference" platform for your SEEKR2 run? No other platforms are currently supported.

**Comment by xfang216** [comment]
I'll have to check with our system admin for the installation. I'll also try running just openMM by itself. 

When running SEEKR2, how do I specify either 'CUDA' or 'Reference'?

**Comment by lvotapka** [comment]
Now that I think about it - SEEKR2 should be handling the platform automatically - you shouldn't need to specify either CUDA or Reference - it will choose one of those based on your input XML file.

So yes, if you could just test your CUDA and Reference platform using OpenMM alone, you might see the problem there.

**Comment by xfang216** [comment]
Tested with openMM alone and it was running.

I wonder if it would be easier to just reinstall SEEKR2 and openMM from scratch. If our system admin is open to it, how would you recommend doing that? Both from source as you suggested? In this case, do we just follow the instructions on https://seekr2.readthedocs.io/en/latest/installation.html?

**Comment by lvotapka** [comment]
Hmm... that is strange, I'm not sure what might be going wrong. But yes, I recommend installing OpenMM 8.0 and seekr2_openmm_plugin both from source, since the conda-forge installation has been having issues with OpenMM 8.0. And yes, that is the correct link.

**Comment by lvotapka** [comment]
We have recently resolved a lot of the issues around installing SEEKR2 with OpenMM 8.1. Please refer to the README and the Documentation instructions for how to do this, but in short, one can do the following steps to install SEEKR2 with OpenMM 8.1:

With the right Conda environment loaded, install the SEEKR2 OpenMM Plugin:

```
conda install -c conda-forge seekr2_openmm_plugin
```
One can test the installation by opening a Python terminal and typing:

```
import seekr2plugin
```

If there is a problem related to not being able to find libOpenMM8.1, one
can try specifying the OpenMM version:

```
conda install -c conda-forge seekr2_openmm_plugin openmm=8.1
```

I'm going to close this issue. Feel free to reopen if more problems arise.
