### ISSUE TITLE
AttributeError running Browndye2

### ISSUE THREAD

**Issue by bensebaer** [seekrcentral/seekr2#6]
Hi Lane,
I have a weird issue running the browndye simulations in seekr2. 

#Using this command:
python /path/to /seekr2/run.py any_bd model.xml 

#I observe the following error:
Traceback (most recent call last):
  File "/home/g035896/Software/seekr2-conda/seekr2/run.py", line 877, in <module>
    run(model, instruction, min_total_simulation_length,
  File "/home/g035896/Software/seekr2-conda/seekr2/run.py", line 652, in run
    bd_milestone_info_to_run = choose_next_simulation_browndye2(
  File "/home/g035896/Software/seekr2-conda/seekr2/run.py", line 62, in choose_next_simulation_browndye2
    bd_transition_counts = data_sample.bd_transition_counts
AttributeError: 'NoneType' object has no attribute 'bd_transition_counts'

In order to identify the issue, I added the following lines to run.py which print data_sample_list and model():
    print(*data_sample_list)
    print(model)

#In the output:
None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None None
<seekr2.modules.common_base.Model object at 0x1552d10e23d0>

For me it seams as if the contents of the model file are not picked up by seekr2 but I don*t fully understand how this is done in the code. 

I observed this issue with all of my prepared inputs but also once running tutorial files. I also have this behavior if I run on one node with 1 or multiple threads or if I use multiple nodes. 

Do you have any idea what is wrong or what I could test to identify the issue?

Best regards
Jens

**Comment by lvotapka** [comment]
Hi Jens,

I think I recently resolved this issue and pushed the bugfix. Are you sure that you've pulled the latest version of the code and done "python setup.py install"?

**Comment by bensebaer** [comment]
Hi Lane,
yes you are right. The issue is fixed by updating the seekr2 package.
